spring:
  application:
    name: exception
  profiles:
    active: local

file:
  dir: C:/project/Study_Project/file/

server:
  tomcat:
    uri-encoding: UTF-8

cloud:
  aws:
    credentials:
      access-key: ${aws.s3.access-key}
      secret-key: ${aws.s3.secret-key}
    region:
      static: ${aws.s3.region}
    stack:
      auto: false
    s3:
      bucket: ${aws.s3.bucket}